file_format: "1"
id: rolio
name: Rolio
type: shield
url: https://github.com/MickiusMousius/rolio
requires: [Nice!Nano]
exposes: [i2c_oled]
features:
  - keys
  - encoder
  - backlight
  - display
siblings:
  - rolio_left
  - rolio_right
